### ISSUE TITLE
Post request problem

### ISSUE THREAD

**Issue by ggao007** [SiyuQian/Stress-recognition-project#15]
**Describe** 
When I do the post request function in the Android code, it shows some problems I cannot fix. It seems that the URL is not good for doing post request, because I am using localhost to do the server website. 
1. When I use ‘http://localhost/api/v1/stress’, the app cannot work well, when the function is started, and the app will be shut down directly.  I try to find the error from the log, but it shows nothing can help, so I try to make a new folder to run this function, and I got the log of this error: ‘NetworkSecurityPolicy.getInstance().isCleartextTrafficPermitted()’, and I search this in the google, I got the solution (https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted) and it works for me.
![image](https://user-images.githubusercontent.com/73207848/112422240-6d665a80-8d95-11eb-8042-b38e102f8b55.png)
2. However, when I merge this code into our project, it works better than before, but it still has errors,  'java.net.ConnectException: Failed to connect to localhost/127.0.0.1:80', also, I try to find a solution on google: (https://stackoverflow.com/questions/36811202/java-net-connectexception-fail-to-connect-to-localhost-127-0-0-1port-8080-co), it seems that I should not use localhost URL, and I also tried to change the localhost to the ‘127.0.0.1’ or delete the 'http://', it still not work.
3. I have tested another URL(https://reqres.in/api/users?page=2), it works well and I send post request successfully, I am not sure what the real reason for this bug. 
![image](https://user-images.githubusercontent.com/73207848/112423013-b79c0b80-8d96-11eb-94cd-aa524da8b666.png)

**Reference**
https://developer.android.com/training/volley/request
https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted
https://stackoverflow.com/questions/36811202/java-net-connectexception-fail-to-connect-to-localhost-127-0-0-1port-8080-co

**Comment by SiyuQian** [comment]
The issue has been solved by using an internal IP address.
